url: https://katiasilvera.github.io/
baseurl:

# Site Settings
title: Katia Silvera
description: "katiasilvera web page"
keywords: "katiasilvera"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/lophiaris.jpg"

exclude: ["Rakefile", "readme.markdown"]
